apiVersion: v1
kind: ReplicationController

metadata:
  name: btcd

spec:
  replicas: 1
  selector:
    name: btcd

  template:
    metadata:
      labels:
        name: btcd
    spec:
      volumes:
        - name: blockchain
          hostPath:
            path: /local/blockchain/
        - name: wallet-source
          hostPath:
            path: /data/btc/wallet-source
        - name: wallet-local
          hostPath:
            path: /local/btcwallet/
        - name: creds
          secret:
            secretName: btc-creds
      containers:
        - name: btcd
          image: localhost:31111/btcd:latest
          ports:
            - name: p2p
              containerPort: 8333
            - name: rpc
              containerPort: 8334
          volumeMounts:
            - name: blockchain
              mountPath: /btc/
            - name: creds
              mountPath: /creds/
        - name: btcwallet
          image: localhost:31111/btcwallet:latest
          ports:
            - name: walletrpc
              containerPort: 8332
          volumeMounts:
            - name: wallet-local
              mountPath: /wallet/
            - name: wallet-source
              mountPath: /source/
            - name: creds
              mountPath: /creds/
