apiVersion: v1
kind: ReplicationController

metadata:
  name: btcd

spec:
  replicas: 1
  selector:
    name: btcd

  template:
    metadata:
      labels:
        name: btcd
    spec:
      volumes:
        - name: blockchain
          hostPath:
            path: /home/core/local/blockchain
        - name: creds
          secret:
            secretName: btcd-creds
      containers:
        - name: btcd
          image: hjfreyer/btcd:latest
          ports:
            - name: p2p
              containerPort: 8333
            - name: rpc
              containerPort: 8334
          volumeMounts:
            - name: blockchain
              mountPath: /btc/
            - name: creds
              mountPath: /creds/
