kind: Service
apiVersion: v1
metadata:
  name: btcsuite
spec:
  ports:
    - name: walletrpc
      port: 8332
      nodePort: 31332
    - name: p2p
      port: 8333
      nodePort: 31333
    - name: rpc
      port: 8334
      nodePort: 31334
  selector:
    cluster: btcsuite
  type: NodePort
  