apiVersion: v1beta3
kind: ReplicationController

metadata:
  name: ddclient

spec:
  replicas: 1
  selector:
    name: ddclient

  template:
    metadata:
      labels:
        name: ddclient
    spec:
      volumes:
        - name: creds
          secret:
            secretName: ddclient-creds
      containers:
        - name: ddclient
          image: hjfreyer/ddclient:latest
          volumeMounts:
            - mountPath: "/creds"
              name: creds
