apiVersion: v1beta3
kind: Pod

metadata:
  name: nginx
  labels:
    name: nginx

spec:
  volumes:
    - name: "host"
      hostPath:
        path: "/home/core/host"
    - name: "certs"
      secret:
        target:
          name: sslcerts
          namespace: default
          kind: Secret
  containers:
    - name: nginx
      image: hjfreyer/nginx
      ports:
        - containerPort: 80
        - containerPort: 443

      volumeMounts:
        - mountPath: "/host"
          name: "host"
        - mountPath: "/certs"
          name: "certs"
