id: nginx-controller2
apiVersion: v1beta1
kind: ReplicationController
desiredState:
  replicas: 1
  # replicaSelector identifies the set of Pods that this
  # replicaController is responsible for managing
  replicaSelector:
    name: nginx
    version: v4
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: nginx
        volumes:
          - name: "host"
            source:
              hostDir:
                path: "/home/core/host"
          - name: "certs"
            source:
              secret:
                target:
                  kind: "Secret"
                  namespace: "default"
                  name: "sslcerts"
        containers:
          - name: nginx
            image: hjfreyer/nginx
            ports:
              - containerPort: 80
              - containerPort: 443

            volumeMounts:
              - mountPath: "/host"
                name: "host"
              - mountPath: "/certs"
                name: "certs"
    # Important: these labels need to match the selector above
    # The api server enforces this constraint.
    labels:
      name: nginx
      version: v4