apiVersion: v1
kind: ReplicationController

metadata:
  name: nginx

spec:
  replicas: 1
  selector:
    name: nginx

  template:
    metadata:
      labels:
        name: nginx
    spec:
      volumes:
        - name: "certs"
          secret:
            secretName: sslcerts
      containers:
        - name: nginx
          image: hjfreyer/nginx
          ports:
            - containerPort: 80
            - containerPort: 443

          volumeMounts:
            - mountPath: "/certs"
              name: "certs"
