kind: ServiceList
apiVersion: v1
items:
  - metadata:
      name: transmission-http
    spec:
      ports:
        - port: 80
          targetPort: http

          # just like the selector in the replication controller,
          # but this time it identifies the set of pods to load balance
          # traffic to.
      selector:
        name: transmission

  - metadata:
      name: transmission-bt
    spec:
      ports:
        - port: 51413
          targetPort: bt
          nodePort: 30003

      selector:
        name: transmission

      type: NodePort

  - metadata:
      name: web
    spec:
      ports:
        - name: http
          port: 80
          nodePort: 30001
        - name: https
          port: 443
          nodePort: 30002

      selector:
        name: nginx

      type: NodePort

  - metadata:
      name: btcd
    spec:
      ports:
        - name: rpc
          port: 8334

      selector:
        name: btcd

