id: transmission-rc
apiVersion: v1beta1
kind: ReplicationController
desiredState:
  replicas: 1
  replicaSelector:
    name: transmission

  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: transmission
        volumes:
          - name: "host"
            source:
              hostDir:
                path: "/home/core/host/transmission"
        containers:
          - name: transmission
            image: hjfreyer/transmission
            ports:
              - name: http
                containerPort: 9091
              - name: bt
                containerPort: 51413

            volumeMounts:
              - mountPath: "/transmission"
                name: "host"
    # Important: these labels need to match the selector above
    # The api server enforces this constraint.
    labels:
      name: transmission