apiVersion: v1
kind: ReplicationController

metadata:
  name: transmission

spec:
  replicas: 1
  selector:
    name: transmission

  template:
    metadata:
      labels:
        name: transmission
    spec:
      volumes:
        - name: host
          hostPath:
            path: /data/transmission
      containers:
        - name: transmission
          image: hjfreyer/transmission:latest
          ports:
            - name: http
              containerPort: 9091
            - name: bt
              containerPort: 51413

          volumeMounts:
            - mountPath: "/transmission"
              name: "host"
