apiVersion: v1
kind: ReplicationController

metadata:
  name: tor

spec:
  replicas: 1
  selector:
    name: tor

  template:
    metadata:
      labels:
        name: tor
    spec:
      containers:
        - name: tor
          image: localhost:31111/tor:latest
          ports:
            - name: socks
              containerPort: 9000
            - name: tor
              containerPort: 9001
