apiVersion: v1
kind: ReplicationController

metadata:
  name: ddclient

spec:
  replicas: 1
  selector:
    name: ddclient

  template:
    metadata:
      labels:
        name: ddclient
    spec:
      volumes:
        - name: creds
          secret:
            secretName: ddclient-creds
      containers:
        - name: ddclient
          image: localhost:31111/ddclient:latest
          volumeMounts:
            - mountPath: "/creds"
              name: creds
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: ddclient-creds
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ddclient-creds
                  key: password